config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', module: 'public', skip: [:passwords], controllers: {
　registrations: "public/registrations",
　sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index]
      resources :comments, only: [:index]
    end
    resources :reviews, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :sizes, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :peoples, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :categories, only: [:index]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'users/my_page' => 'users#show'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/update'
    get 'users/check'
    patch 'users/withdraw'
    # レビューは商品に紐付いているため親子関係のルーティング
    resources :items, only: [:show] do
      resource :favorites, only: [:create, :destroy] # 「1人のユーザーは1つの商品に対して1回しかいいねできない」という仕様であるため、｢resources｣ではなく｢resource｣
      resources :reviews, only: [:show, :create] do
        resource :r_favorites, only: [:create, :destroy]
        resources :comments, only: [:create]
      end
    end
    resources :reviews, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :show]
    resources :sizes, only: [:index, :show]
    resources :peoples, only: [:index, :show]
    resources :makers, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/category_tag.rb
class CategoryTag < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true

  has_many :genre_tags, dependent: :destroy
  has_many :items, through: :genre_tags, dependent: :destroy
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  belongs_to :item
  belongs_to :genre
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true

  has_many :reviews, dependent: :destroy

  has_many :genre_tags, dependent: :destroy
  has_many :genres, through: :genre_tags, dependent: :destroy

  has_many :size_tags, dependent: :destroy
  has_many :sizes, through: :size_tags, dependent: :destroy

  has_many :people_tags, dependent: :destroy
  has_many :peoples, through: :people_tags, dependent: :destroy

  has_many :maker_tags, dependent: :destroy
  has_many :makers, through: :maker_tags, dependent: :destroy

  has_many :favorites, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/maker.rb
class Maker < ApplicationRecord

  validates :name, presence: true

  has_many :maker_tags, dependent: :destroy
  has_many :items, through: :maker_tags, dependent: :destroy
end

app/models/maker_tag.rb
class MakerTag < ApplicationRecord
  belongs_to :item
  belongs_to :maker
end

app/models/people.rb
class People < ApplicationRecord

  validates :name, presence: true

  has_many :people_tags, dependent: :destroy
  has_many :items, through: :people_tags, dependent: :destroy
end

app/models/people_tag.rb
class PeopleTag < ApplicationRecord
  belongs_to :item
  belongs_to :people
end

app/models/r_favorite.rb
class RFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :item

  has_many :comments, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}

  # 引数で渡されたユーザidがR_favoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def r_favorited_by?(user)
    r_favorites.exists?(user_id: user.id)
  end
end

app/models/size.rb
class Size < ApplicationRecord

  validates :name, presence: true

  has_many :size_tags, dependent: :destroy
  has_many :items, through: :size_tags, dependent: :destroy
end

app/models/size_tag.rb
class SizeTag < ApplicationRecord
  belongs_to :item
  belongs_to :size
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :user_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :family, presence: true

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 退会済みかの確認。is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # enumの定義を設定
  enum gender: { male: 0, female: 1, non_binary: 2 }
end

app/controllers/admin/peoples_controller.rb
class Admin::PeoplesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @people = People.new
    @peoples = People.all
  end

  def create
    @people = People.new(people_params)
    if @people.save
    # 元の画面に戻るリダイレクト
      redirect_to request.referer
    else
      @peoples = People.all
      render :index
    end
  end

  def show
    @peoples = People.all
    @people = People.find(params[:id])
  end

  def edit
    @people = People.find(params[:id])
  end

  def update
    @people = People.find(params[:id])
    if @people.update(people_params)
      redirect_to admin_peoples_path
    else
      render :edit
    end
  end

  def destroy
    people = People.find(params[:id])
    people.destroy
    redirect_to admin_peoples_path
  end

  private

  def people_params
    params.require(:people).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end

  protected

  def configure_permitted_parameters
    # ユーザー登録時と編集時にそれぞれ必要な項目の指定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
  end
end

app/helpers/admin/peoples_helper.rb
module Admin::PeoplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/peoples/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <h3 class="table-secondary text-center">適正人数名称編集</h3>
    </div>
    <div class="col-md-6"></div>
  </div>

  <%= form_with model: @people, url:admin_people_path do |f| %>
  <div class="row justify-content-center mt-4">
    <div class="col-md-9">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>適正人数名称</th>
            <td>
              <%= f.text_field :name %>
            </td>
            <td>
              <%= f.submit "変更を保存", class: 'btn btn-sm btn-success' %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/peoples/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-3">
      <h3 class="table-secondary text-center">適正人数名称一覧</h3>
    </div>
    <div class="col-md-7"></div>
  </div>

  <%= form_with model: @people, url:admin_peoples_path do |f| %>
  <div class="row justify-content-center mt-4">
    <div class="col-md-9">
      <% if @people.errors.any? %>
        <font color="red">※未入力です。入力してから再度登録ボタンを押下してください。</font>
      <% end %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>適正人数の名称</th>
            <td>
              <%= f.text_field :name %>
            </td>
            <td>
              <%= f.submit "新規登録", class: 'btn btn-sm btn-success' %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>

  <div class="row justify-content-center mt-3">
    <div class="col-md-10">
      <table class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th>ID</th>
            <th>名称</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @peoples.each do |people| %>
          <tr>
            <td>
              <%= people.id %>
            </td>
            <td>
              <%= link_to people.name, admin_people_path(people.id) %>
            </td>
            <td>
              <%= link_to "編集する", edit_admin_people_path(people.id), class: 'btn btn-sm btn-success' %>
              <%= link_to "削除する", admin_people_path(people.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/peoples/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-3">
      <h3 class="table-secondary text-center"><%= @people.name %>一覧</h3>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-1 text-center">
      <%= link_to new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-lg"></i>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-md-10">
      <table class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
          </tr>
        </thead>
        <tbody>
        <% @people.items.each do |item| %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= link_to admin_item_path(item) do %>
                <%= item.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>