config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', module: 'public', skip: [:passwords], controllers: {
　registrations: "public/registrations",
　sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index]
      resources :comments, only: [:index]
    end
    resources :reviews, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :sizes, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :peoples, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :categories, only: [:index]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'users/my_page' => 'users#show'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/update'
    get 'users/check'
    patch 'users/withdraw'
    # レビューは商品に紐付いているため親子関係のルーティング
    resources :items, only: [:show] do
      resource :favorites, only: [:create, :destroy] # 「1人のユーザーは1つの商品に対して1回しかいいねできない」という仕様であるため、｢resources｣ではなく｢resource｣
      resources :reviews, only: [:show, :create] do
        resource :r_favorites, only: [:create, :destroy]
        resources :comments, only: [:create]
      end
    end
    resources :reviews, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :show]
    resources :sizes, only: [:index, :show]
    resources :peoples, only: [:index, :show]
    resources :makers, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/category_tag.rb
class CategoryTag < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true

  has_many :genre_tags, dependent: :destroy
  has_many :items, through: :genre_tags, dependent: :destroy
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  belongs_to :item
  belongs_to :genre
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true

  has_many :reviews, dependent: :destroy

  has_many :genre_tags, dependent: :destroy
  has_many :genres, through: :genre_tags, dependent: :destroy

  has_many :size_tags, dependent: :destroy
  has_many :sizes, through: :size_tags, dependent: :destroy

  has_many :people_tags, dependent: :destroy
  has_many :peoples, through: :people_tags, dependent: :destroy

  has_many :maker_tags, dependent: :destroy
  has_many :makers, through: :maker_tags, dependent: :destroy

  has_many :favorites, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/maker.rb
class Maker < ApplicationRecord

  validates :name, presence: true

  has_many :maker_tags, dependent: :destroy
  has_many :items, through: :maker_tags, dependent: :destroy
end

app/models/maker_tag.rb
class MakerTag < ApplicationRecord
  belongs_to :item
  belongs_to :maker
end

app/models/people.rb
class People < ApplicationRecord

  validates :name, presence: true

  has_many :people_tags, dependent: :destroy
  has_many :items, through: :people_tags, dependent: :destroy
end

app/models/people_tag.rb
class PeopleTag < ApplicationRecord
  belongs_to :item
  belongs_to :people
end

app/models/r_favorite.rb
class RFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :item

  has_many :comments, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}

  # 引数で渡されたユーザidがR_favoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def r_favorited_by?(user)
    r_favorites.exists?(user_id: user.id)
  end
end

app/models/size.rb
class Size < ApplicationRecord

  validates :name, presence: true

  has_many :size_tags, dependent: :destroy
  has_many :items, through: :size_tags, dependent: :destroy
end

app/models/size_tag.rb
class SizeTag < ApplicationRecord
  belongs_to :item
  belongs_to :size
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :user_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :family, presence: true

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 退会済みかの確認。is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # enumの定義を設定
  enum gender: { male: 0, female: 1, non_binary: 2 }
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user = User.find(params[:user_id])
    @reviews = @user.reviews.all
  end

  def show
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to request.referer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end

  protected

  def configure_permitted_parameters
    # ユーザー登録時と編集時にそれぞれ必要な項目の指定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/reviews/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-3">
      <h3 class="table-secondary text-center">レビュー履歴一覧</h3>
    </div>
    <div class="col-md-9">
      <%= link_to "会員詳細へ戻る", admin_user_path(@user.id), class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

  <div class="row justify-content-center mt-3 ml-3">
    <div class="col-md-12">
      <table>
        <thead>
          <tr>
            <th class="col-md-2 text-center table-bordered table-secondary">投稿日時</th>
            <th class="col-md-2 text-center table-bordered table-secondary">商品名</th>
            <th class="col-md-2 text-center table-bordered table-secondary">いいね・コメント</th>
            <th class="col-md-5 text-center table-bordered table-secondary">投稿内容</th>
            <th class="col-md-1"></th>
          </tr>
        </thead>
      <% @reviews.each do |review| %>
        <tbody>
          <tr>
            <td class="text-center table-bordered">
              <%= review.created_at.strftime('%Y/%m/%d') %>
            </td>
            <td class="text-center table-bordered">
              <%= review.item.name %>
            </td>
            <td class="text-center table-bordered">
              <i class="far fa-heart" style="color: #f21ceb;"></i><%= review.r_favorites.count %>件　<i class="far fa-comment" style="color: #3cb4d3;"></i><%= review.comments.count %>件
            </td>
            <td class="pl-1 table-bordered">
              <%= review.body %>
            </td>
            <td class="pl-1">
              <%= link_to "削除する", admin_review_path(review.id), method: :delete, class: 'btn btn-sm btn-danger' %>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<h1>Admin::Reviews#show</h1>
<p>Find me in app/views/admin/reviews/show.html.erb</p>