config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', module: 'public', skip: [:passwords], controllers: {
　registrations: "public/registrations",
　sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index]
      resources :comments, only: [:index]
    end
    resources :reviews, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :sizes, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :peoples, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :categories, only: [:index]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'users/my_page' => 'users#show'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/update'
    get 'users/check'
    patch 'users/withdraw'
    # レビューは商品に紐付いているため親子関係のルーティング
    resources :items, only: [:show] do
      resource :favorites, only: [:create, :destroy] # 「1人のユーザーは1つの商品に対して1回しかいいねできない」という仕様であるため、｢resources｣ではなく｢resource｣
      resources :reviews, only: [:show, :create] do
        resource :r_favorites, only: [:create, :destroy]
        resources :comments, only: [:create]
      end
    end
    resources :reviews, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :show]
    resources :sizes, only: [:index, :show]
    resources :peoples, only: [:index, :show]
    resources :makers, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/category_tag.rb
class CategoryTag < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true

  has_many :genre_tags, dependent: :destroy
  has_many :items, through: :genre_tags, dependent: :destroy
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  belongs_to :item
  belongs_to :genre
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true

  has_many :reviews, dependent: :destroy

  has_many :genre_tags, dependent: :destroy
  has_many :genres, through: :genre_tags, dependent: :destroy

  has_many :size_tags, dependent: :destroy
  has_many :sizes, through: :size_tags, dependent: :destroy

  has_many :people_tags, dependent: :destroy
  has_many :peoples, through: :people_tags, dependent: :destroy

  has_many :maker_tags, dependent: :destroy
  has_many :makers, through: :maker_tags, dependent: :destroy

  has_many :favorites, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/maker.rb
class Maker < ApplicationRecord

  validates :name, presence: true

  has_many :maker_tags, dependent: :destroy
  has_many :items, through: :maker_tags, dependent: :destroy
end

app/models/maker_tag.rb
class MakerTag < ApplicationRecord
  belongs_to :item
  belongs_to :maker
end

app/models/people.rb
class People < ApplicationRecord

  validates :name, presence: true

  has_many :people_tags, dependent: :destroy
  has_many :items, through: :people_tags, dependent: :destroy
end

app/models/people_tag.rb
class PeopleTag < ApplicationRecord
  belongs_to :item
  belongs_to :people
end

app/models/r_favorite.rb
class RFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :item

  has_many :comments, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}

  # 引数で渡されたユーザidがR_favoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def r_favorited_by?(user)
    r_favorites.exists?(user_id: user.id)
  end
end

app/models/size.rb
class Size < ApplicationRecord

  validates :name, presence: true

  has_many :size_tags, dependent: :destroy
  has_many :items, through: :size_tags, dependent: :destroy
end

app/models/size_tag.rb
class SizeTag < ApplicationRecord
  belongs_to :item
  belongs_to :size
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :user_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :family, presence: true

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 退会済みかの確認。is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # enumの定義を設定
  enum gender: { male: 0, female: 1, non_binary: 2 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :user_name, :age, :gender, :family, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end

  protected

  def configure_permitted_parameters
    # ユーザー登録時と編集時にそれぞれ必要な項目の指定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <h3 class="table-secondary text-center"><%= @user.last_name %><%= @user.first_name %>さんの会員情報編集</h3>
    </div>
    <div class="col-md-5"></div>
  </div>

  <%= form_with model: @user, url: admin_user_path, method: :patch, local: true do |f| %>
  <div class="row justify-content-center mt-3">
    <div class="col-md-9">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name, autofocus: true %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.email_field :email, autocomplete: "email" %></td>
          </tr>
          <tr>
            <th>ユーザーネーム</th>
            <td><%= f.text_field :user_name %></td>
          </tr>
          <tr>
            <th>年齢</th>
            <td><%= f.text_field :age %>歳</td>
          </tr>
          <tr>
            <th>性別</th>
            <td>
              <%= f.radio_button :gender, User.genders.key(0) %><%= f.label :gender_male, User.genders_i18n[:male] %>
              <%= f.radio_button :gender, User.genders.key(1) %><%= f.label :gender_female, User.genders_i18n[:female] %>
              <%= f.radio_button :gender, User.genders.key(2) %><%= f.label :gender_non_binary, User.genders_i18n[:non_binary] %>
            </td>
          </tr>
          <tr>
            <th>家族構成</th>
            <td>
              <%= f.text_field :family %>
            </td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <!--ラジオボタン機能で二択のチェックボックス作成-->
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted_false, "有効" %>

              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted_true, "退会" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-md-3"></div>
    <div class="col-md-7">
      <%= f.submit "変更を保存", class: 'btn btn-sm btn-success' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-2">
      <h3 class="table-secondary text-center">会員一覧</h3>
    </div>
    <div class="col-md-8"></div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-md-8">
      <table class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= user.id %>
            </td>
            <td>
              <%= link_to admin_user_path(user.id) do %>
                <%= user.last_name %><%= user.first_name %>
              <% end %>
            </td>
            <td>
              <%= user.email %>
            </td>
            <td>
              <% if user.is_deleted == false %>
                <p class="text-success mb-0"><%= "有効" %></p>
              <% else %>
                <p class="text-danger mb-0"><%= "退会" %></p>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
<div>
  <%= paginate @users %>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-2"></div>
    <div class="col-md-5">
      <h3 class="table-secondary text-center"><%= @user.last_name %><%= @user.first_name %>さんの会員詳細</h3>
    </div>
    <div class="col-md-5"></div>
  </div>

  <div class="row justify-content-center mt-2">
    <div class="col-md-6">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @user.last_name %> <%= @user.first_name %></td>
          </tr>
          <tr>
            <th>ユーザーネーム</th>
            <td><%= @user.user_name %></td>
          </tr>
          <tr>
            <th>年齢</th>
            <td><%= @user.age %>歳</td>
          </tr>
          <tr>
            <th>性別</th>
            <td><%= @user.gender_i18n %></td>
          </tr>
          <tr>
            <th>家族構成</th>
            <td><%= @user.family %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <% if @user.is_deleted == false %>
                <strong class="text-success"><%= "有効" %></strong>
              <% else %>
                <strong class="text-danger"><%= "退会" %></strong>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row justify-content-center mt-2">
    <div class="col-md-6"></div>
    <div class="col-md-6">
      <%= link_to "編集する", edit_admin_user_path, class: 'btn btn-sm btn-success' %>
    </div>
  </div>

  <div class="row justify-content-center mt-4">
    <div class="col-md-2"></div>
    <div class="col-md-3">
      <h3 class="table-secondary text-center">投稿履歴</h3>
    </div>
    <div class="col-md-7"></div>
  </div>

  <div class="row justify-content-center mt-2">
    <div class="col-md-2">
      <%= link_to "レビュー履歴を見る", admin_user_reviews_path(@user.id), class: 'btn btn-sm btn-primary' %>
    </div>
    <div class="col-md-2">
      <%= link_to "コメント履歴を見る", admin_user_comments_path(@user.id), class: 'btn btn-sm btn-primary' %>
    </div>
  </div>

</div>