config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', module: 'public', skip: [:passwords], controllers: {
　registrations: "public/registrations",
　sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index]
      resources :comments, only: [:index]
    end
    resources :reviews, only: [:destroy]
    resources :comments, only: [:destroy]
    resources :genres, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :sizes, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :peoples, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :makers, only: [:index, :create, :show, :edit, :update, :destroy]
    resources :categories, only: [:index]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get 'users/my_page' => 'users#show'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/update'
    get 'users/check'
    patch 'users/withdraw'
    # レビューは商品に紐付いているため親子関係のルーティング
    resources :items, only: [:show] do
      resource :favorites, only: [:create, :destroy] # 「1人のユーザーは1つの商品に対して1回しかいいねできない」という仕様であるため、｢resources｣ではなく｢resource｣
      resources :reviews, only: [:show, :create] do
        resource :r_favorites, only: [:create, :destroy]
        resources :comments, only: [:create]
      end
    end
    resources :reviews, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :show]
    resources :sizes, only: [:index, :show]
    resources :peoples, only: [:index, :show]
    resources :makers, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/category_tag.rb
class CategoryTag < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true

  has_many :genre_tags, dependent: :destroy
  has_many :items, through: :genre_tags, dependent: :destroy
end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord
  belongs_to :item
  belongs_to :genre
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true

  has_many :reviews, dependent: :destroy

  has_many :genre_tags, dependent: :destroy
  has_many :genres, through: :genre_tags, dependent: :destroy

  has_many :size_tags, dependent: :destroy
  has_many :sizes, through: :size_tags, dependent: :destroy

  has_many :people_tags, dependent: :destroy
  has_many :peoples, through: :people_tags, dependent: :destroy

  has_many :maker_tags, dependent: :destroy
  has_many :makers, through: :maker_tags, dependent: :destroy

  has_many :favorites, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/maker.rb
class Maker < ApplicationRecord

  validates :name, presence: true

  has_many :maker_tags, dependent: :destroy
  has_many :items, through: :maker_tags, dependent: :destroy
end

app/models/maker_tag.rb
class MakerTag < ApplicationRecord
  belongs_to :item
  belongs_to :maker
end

app/models/people.rb
class People < ApplicationRecord

  validates :name, presence: true

  has_many :people_tags, dependent: :destroy
  has_many :items, through: :people_tags, dependent: :destroy
end

app/models/people_tag.rb
class PeopleTag < ApplicationRecord
  belongs_to :item
  belongs_to :people
end

app/models/r_favorite.rb
class RFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :item

  has_many :comments, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 空をバリデーション、文字数制限
  validates :body, presence: true, length: {maximum: 100}

  # 引数で渡されたユーザidがR_favoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalse
  def r_favorited_by?(user)
    r_favorites.exists?(user_id: user.id)
  end
end

app/models/size.rb
class Size < ApplicationRecord

  validates :name, presence: true

  has_many :size_tags, dependent: :destroy
  has_many :items, through: :size_tags, dependent: :destroy
end

app/models/size_tag.rb
class SizeTag < ApplicationRecord
  belongs_to :item
  belongs_to :size
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :user_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :family, presence: true

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :r_favorites, dependent: :destroy

  # 退会済みかの確認。is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # enumの定義を設定
  enum gender: { male: 0, female: 1, non_binary: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end

  protected

  def configure_permitted_parameters
    # ユーザー登録時と編集時にそれぞれ必要な項目の指定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :user_name, :age, :gender, :family])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadenReference</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/d60d313785.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <% if admin_signed_in? %>
            <%= link_to "家電リファレンス", root_path, class:"header-title navbar-brand text-dark" %>
          <% else %>
            <%= link_to "家電リファレンス", root_path, class:"header-title navbar-brand text-dark" %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <% if admin_signed_in? %>
              <% if request.fullpath.include? "/admin" %>
              <div>
                <%= form_with url:admin_root_path, method: :get, local: true do |f| %>
                  <%= f.text_field :name, placeholder:"型番入力" %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li>
                    <%= link_to admin_categories_path, class: 'nav-link text-dark' do %>
                      カテゴリ一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
                      家電一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                      会員一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                      ログアウト
                    <% end %>
                  </li>
                </ul>
              </div>
              <% else %>
              <div>
                <%= form_with url:root_path, method: :get, local: true do |f| %>
                  <%= f.text_field :name, placeholder:"型番入力" %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li>
                    <%= link_to about_path, class: 'nav-link text-dark' do %>
                      アバウト
                    <% end %>
                  </li>
                  <li>
                    <%= link_to root_path, class: 'nav-link text-dark' do %>
                      家電一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                      新規登録
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                      ログイン
                    <% end %>
                  </li>
                </ul>
              </div>
              <% end %>
            <% elsif user_signed_in? %>
              <div>
                <%= form_with url:root_path, method: :get, local: true do |f| %>
                  <%= f.text_field :name, placeholder:"型番入力" %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li>
                    <%= link_to about_path, class: 'nav-link text-dark' do %>
                      アバウト
                    <% end %>
                  </li>
                  <li>
                    <%= link_to root_path, class: 'nav-link text-dark' do %>
                      家電一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to users_my_page_path, class: 'nav-link text-dark' do %>
                      マイページ
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                      ログアウト
                    <% end %>
                  </li>
                </ul>
              </div>
            <% else %>
              <div>
                <%= form_with url:root_path, method: :get, local: true do |f| %>
                  <%= f.text_field :name, placeholder:"型番入力" %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li>
                    <%= link_to about_path, class: 'nav-link text-dark' do %>
                      アバウト
                    <% end %>
                  </li>
                  <li>
                    <%= link_to root_path, class: 'nav-link text-dark' do %>
                      家電一覧
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                      新規登録
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                      ログイン
                    <% end %>
                  </li>
                </ul>
              </div>
            <% end %>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="bg-light text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>kaden_reference</p>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3"></h6>
            <ul class="p-0 list-unstyled">
              <li>
              </li>
              <li>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>